french_dict = {
    "House" : "Maison" ,
    "Car" : "Voiture" ,
    "Book" : "Livre",
    "Water" : "Eau" ,
    "Food" : "Nourriture",
    "Friend" : "Amie",
    "Love" : "Amour",
    "Sun" : "Soleil",
    "Moon" : "Lune",
    "Tree" : "Arbre",
    "sky" : "Ciel",
    "Flower" : "Fleur",
    "Mountain" : "Montagne",
    "River" : "Riviere",
    "City" : "Ville",
    "Dog" : "Chien",
    "Cat" : "Chat",
    "Music" : "Musique",
    "Family" : "Famille",
    "Dream" : "Reve",
}
print(french_dict)